config/routes.rb
ScoringSystem::Application.routes.draw do  
  resources :departments
  resources :admins
  resources :employees
  resources :masters
  resources :department_marks
  resources :master_marks
  resources :sessions, only: [:new, :create, :destroy]
  root :to => 'home#index'
  match '/sys' => 'SysManagements#index'
  match '/sys/new' => 'SysManagements#new'
  match '/sys/result' => 'SysManagements#show'
  match '/sys/getresult' => 'SysManagements#result'
  match '/sys/detail'=>'SysManagements#detail'

  match '/sys/getterm'=>'SysManagements#getterm'
  match '/sys/info'=>'SysManagements#info'
  match '/sys/signup' => 'Employees#new'
  match '/sys/echarts'=>'SysManagements#echarts'
  match '/employees/:id' => 'Employees#show'  
  match '/masters/:id' => 'Masters#show' 
  match '/admins/:id' => 'Admins#show'  
  match '/signin',  to: 'Sessions#new',         via: 'get'
  match '/signout', to: 'Sessions#destroy',     via: 'delete'

  match '/mark' => 'Marks#index'
  match '/mark/submit' => 'Marks#submit'
  match '/mark/score' => 'Marks#score'

end

app/models/department.rb
class Department < ActiveRecord::Base
  attr_accessible :name
  has_many :masters
  has_many :employees

  has_many :department_masks

  #返回当前主管某期平均分(phase:20160520)
  def term_score(phase)
    m = DepartmentMark.select('round(avg(score),2) as point').where('term_phase=? and department_id=?',phase,self.id)
    m.first.point
  end

  #返回当前主管某月平均分(month:201605)
  def month_score(month)
    m = DepartmentMark.select('round(avg(score),2) as point').where('left(term_phase,6)=? and department_id=?',month,self.id)
    m.first.point
  end


  #返回所有主管某期平均分(phase:20160520)
  def self.term_score(phase)
    DepartmentMark.select('round(avg(score),2) as point').where('term_phase=?',phase).group(self.id)
  end

  #返回所有主管某月平均分(month:201605)
  def self.month_score(month)
    DepartmentMark.select('round(avg(score),2) as point').where('left(term_phase,6)=?',month).group(self.id)
  end

end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
	before_filter :authorize
  
	def show
		@department = Department.find(params[:id])
	    respond_to do |format|
	      format.html # show.html.erb
	      format.json { render json: @department }
	    end
	end

	def new
		@department = Department.new
	    respond_to do |format|
	      format.html # new.html.erb
	      format.json { render json: @department }
	    end
	end


	def edit
		@department = Department.find(params[:id])
	end


	def create
		@department = Department.new(params[:department])

		respond_to do |format|
		  if @department.save
		    format.html { redirect_to @department, notice: 'Department was successfully created.' }
		    format.json { render json: @department, status: :created, location: @department }
		  else
		    format.html { render action: "new" }
		    format.json { render json: @department.errors, status: :unprocessable_entity }
		  end
		end
	end


	def update
		@department = Department.find(params[:id])

		respond_to do |format|
		  if @department.update_attributes(params[:department])
		    format.html { redirect_to @department, notice: 'Department was successfully updated.' }
		    format.json { head :no_content }
		  else
		    format.html { render action: "edit" }
		    format.json { render json: @department.errors, status: :unprocessable_entity }
		  end
		end
	end

	
 
end

app/views/departments/_form.html.erb
<%= form_for @product, :html => { :class => "form-horizontal product" } do |f| %>

  <% if @product.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :image_url, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :image_url, :class => 'form-control' %>
    </div>
    <%=f.error_span(:image_url) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
     <%= f.text_area :description, :class => 'form-control' %> 

    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <%= f.label :price, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.number_field :price, :class => 'form-control' %>
    </div>
    <%=f.error_span(:price) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/departments/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/departments/index.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <!-- <th><%= model_class.human_attribute_name(:id) %></th> -->
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:mobile) %></th>
      <th><%= model_class.human_attribute_name(:department_id) %></th>
      <th><%= model_class.human_attribute_name(:type) %></th>  
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td style="display: none" id="employeeid"><%= link_to employee.id, employee_path(employee) %></td>
        <td><%= employee.name %></td>
        <td><%= employee.mobile %></td>
        <td><%= employee.department_id %></td>
        <td><%= employee.type %></td>
        <td>
           <!-- <input type="button"  value="edit" class="1" ></input> -->
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_employee_path(employee), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      employee_path(employee),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>      
    <% end %>
  </tbody>
</table>

app/views/departments/show.html.erb
<h1><%= @department.name %></h1>

部门主管人数：<%= @department.masters.count %><br />
部门员工人数：<%= @department.employees.count %><br />
<br /><br />
<%= link_to '编辑', edit_department_path(@department) %>