config/routes.rb
ScoringSystem::Application.routes.draw do  
  resources :departments
  resources :admins
  resources :employees
  resources :masters
  resources :department_marks
  resources :master_marks
  resources :sessions, only: [:new, :create, :destroy]
  root :to => 'home#index'
  match '/sys' => 'SysManagements#index'
  match '/sys/new' => 'SysManagements#new'
  match '/sys/result' => 'SysManagements#show'
  match '/sys/getresult' => 'SysManagements#result'
  match '/sys/detail'=>'SysManagements#detail'

  match '/sys/getterm'=>'SysManagements#getterm'
  match '/sys/info'=>'SysManagements#info'
  match '/sys/signup' => 'Employees#new'
  match '/sys/echarts'=>'SysManagements#echarts'
  match '/employees/:id' => 'Employees#show'  
  match '/masters/:id' => 'Masters#show' 
  match '/admins/:id' => 'Admins#show'  
  match '/signin',  to: 'Sessions#new',         via: 'get'
  match '/signout', to: 'Sessions#destroy',     via: 'delete'

  match '/mark' => 'Marks#index'
  match '/mark/submit' => 'Marks#submit'
  match '/mark/score' => 'Marks#score'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ScoringSystem" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "echarts.min" %>
    <%= javascript_include_tag "bootstrap-table-export" %>
    <%= javascript_include_tag "FileSaver.min" %>
    <%= javascript_include_tag "tableExport" %>
       
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">KID-评分系统</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "首页", root_path  %></li>                        
            <% if sign_in? %>
              <% if admin? %>
              <li id="fat-menu" class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    你好,【<%= current_employee["name"] %>】<span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">                      
                      <li><%= link_to "编辑资料", edit_employee_path(current_employee) %></li>
                      <li><%= link_to "开始打分", '/mark' %></li>
                      <li class="divider"></li>
                      <li>
                        <%= link_to "后台管理", '/sys' %>
                      </li>
                      <li>                        
                        <%= link_to "退出登录", signout_path, method:"delete" %>
                      </li>             
                  </ul>
               </li>
              <% else %>            
              <li id="fat-menu" class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    你好,【<%= current_employee["name"] %>】<span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                      <li><%= link_to "编辑资料", edit_employee_path(current_employee) %></li>
                      <li><%= link_to "开始打分", '/mark' %></li>
                      <li class="divider"></li>
                      <li>
                        <%= link_to "退出登录", signout_path, method:"delete" %>
                      </li>             
                  </ul>
               </li>
               <% end %>
             <% else %>
             <li><%= link_to "Sign in",signin_path %></li>
             <% end %>

          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
       
      </div><!--/row-->

      <!-- <footer>
        <p>&copy; Tony 2016</p>
      </footer> -->

    </div> <!-- /container -->

  </body>
</html>